name: earthdaily-processor
channels:
 - conda-forge
 - defaults
dependencies:
  - python>3.11
  - ipykernel
  - python-dotenv>=0.5.1
  - geojson
  - pyproj
  - zarr
  - pip 
  - pip:
    # aws
    - boto3
    # azure
    - azure-storage-blob
    - earthdaily==0.0.6
    - jupyter
    - matplotlib
    - numpy 
    - scipy
    - geogif
    - fastapi
    - pydantic
    - byoa==0.1.0a2
